name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install packages
      run: make install

    - name: lint
      run: make lint

    - name: test
      run: make test

    - name: format
      run: make format

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
